<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_H v Tn_FullName</name>
   <tag></tag>
   <elementGuidId>4d16d706-308a-4406-96cd-c83071ae33f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FullName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FullName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f30971e3-1f39-463e-8e06-cc932bbbf218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b9cc3147-1589-4caa-838c-6e412198f297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Họ và Tên</value>
      <webElementGuid>603a4e51-b559-4fc6-9faa-3aa831ec59e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>36713c2b-f4a1-4d99-b5b5-47c4476dfd88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Vui lòng nhập Họ Tên</value>
      <webElementGuid>c12c126a-0fbc-49bb-8592-96fd4ed8ef75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FullName</value>
      <webElementGuid>666b826f-b99e-4dbc-9782-7bacad03862b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FullName</value>
      <webElementGuid>421d89a6-034a-49f1-a07c-41252670b3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FullName&quot;)</value>
      <webElementGuid>1a26b7ef-6891-4025-835c-4209f2b02469</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FullName']</value>
      <webElementGuid>b2c64b53-e799-460e-985f-70889d87bed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>e0a0f41b-e6ef-4da1-9b61-b3010a41f5d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Họ và Tên' and @id = 'FullName' and @name = 'FullName']</value>
      <webElementGuid>f274b9ed-6825-49ef-a9a7-ba03ef2ceb57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
