<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Lin h nhanh_pe-7s-users</name>
   <tag></tag>
   <elementGuidId>2a4b0640-1392-46ad-9f64-37240cc1ee15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='settingButton']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.pe-7s-users</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ee4fd713-14cc-49c6-af00-61b46b9eee67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pe-7s-users</value>
      <webElementGuid>0410146e-4498-4490-a3b8-058d9e331b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;settingButton&quot;)/i[@class=&quot;pe-7s-users&quot;]</value>
      <webElementGuid>5ee7fe60-d1e0-4c43-8144-a6f979396233</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='settingButton']/i</value>
      <webElementGuid>18673167-b170-4aa8-8469-526c9c4c6fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/button/i</value>
      <webElementGuid>988d695c-83c9-4cf1-b56d-9e3e5bab9c3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
