<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clickhinh</name>
   <tag></tag>
   <elementGuidId>7d386992-e623-4b87-b657-6e842a562096</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='all-items']/div/div/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>44ddf781-160c-4cb3-acd2-4244e19fee33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>1b9aa5f8-333f-4a52-81de-c82d3f695fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>9061da84-b094-45e2-a22b-a9bfd8d81737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-full</value>
      <webElementGuid>4ab37a4a-9747-44b6-bcad-6578cec2d4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/products/serum.jpg</value>
      <webElementGuid>4626ee74-b655-4930-a768-cced9e544c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;all-items&quot;)/div[@class=&quot;product-item-wrap row&quot;]/div[@class=&quot;col-xl-3 col-lg-4 col-sm-6&quot;]/div[@class=&quot;product-item&quot;]/div[@class=&quot;product-img img-zoom-effect&quot;]/a[1]/img[@class=&quot;img-full&quot;]</value>
      <webElementGuid>b776d002-67ce-4350-b9ca-73b2b46e955e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='all-items']/div/div/div/div/a/img</value>
      <webElementGuid>45fc00e8-fb35-4cc2-a40e-8b1a6adb5dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/a/img</value>
      <webElementGuid>b2aef21c-ec6a-4331-a24b-e60826b39f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/products/serum.jpg']</value>
      <webElementGuid>d2ad165d-8fff-43e4-bb0b-66fa48bbec61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
