<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>soluonggiohang</name>
   <tag></tag>
   <elementGuidId>9a01b0d3-6856-4369-bdd7-140685bf8f54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.quantity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>35f55a9b-fda8-470e-97eb-dda5d20ae94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>80f855f3-edeb-4c37-9521-cf02f9fa1ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3c40dc94-25a8-411e-99c4-1ef055dc8227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;sizes customelements history pointerevents postmessage postmessage-structuredclones webgl websockets cssanimations csscolumns csscolumns-width csscolumns-span csscolumns-fill csscolumns-gap csscolumns-rule csscolumns-rulecolor csscolumns-rulestyle csscolumns-rulewidth csscolumns-breakbefore csscolumns-breakafter csscolumns-breakinside flexbox picture srcset webworkers&quot;]/body[1]/div[@class=&quot;main-wrapper&quot;]/header[@class=&quot;main-header_area position-relative&quot;]/div[@class=&quot;header-middle py-5&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;header-middle-wrap&quot;]/div[@class=&quot;header-right&quot;]/ul[1]/li[@class=&quot;minicart-wrap me-3 me-lg-0&quot;]/a[@class=&quot;toolbar-btn&quot;]/span[@class=&quot;quantity&quot;]</value>
      <webElementGuid>cfd6de5e-da23-4887-b1bb-3bdbcf87c688</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập'])[1]/following::span[1]</value>
      <webElementGuid>68a1df2e-5e52-4185-a853-90ae1370ab97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng ký tài khoản'])[1]/following::span[1]</value>
      <webElementGuid>1d67f619-8e70-45d9-a352-4c076f081bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang chủ'])[2]/preceding::span[1]</value>
      <webElementGuid>993a2040-210f-4996-83ef-4042015af2b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop'])[1]/preceding::span[1]</value>
      <webElementGuid>9c525c75-a16f-4b49-861b-c2e1e79164ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0']/parent::*</value>
      <webElementGuid>41a92379-de07-4bad-a756-cdff437d1db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>e82fa75f-4c2f-45a7-8341-629ab8065bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '0' or . = '0')]</value>
      <webElementGuid>4dc25ba1-0e99-4b3f-89d5-2b9c15673e3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
