<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Thng tin ti khon</name>
   <tag></tag>
   <elementGuidId>d7cc84c5-02b3-4648-bcd4-0fcdca8c6339</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#account-dashboard-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='account-dashboard-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fb6d4aeb-5e1a-4c7d-a1ec-ba322cb606ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link active</value>
      <webElementGuid>dfab3abd-3e40-4255-85c4-b491a83cfc80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>account-dashboard-tab</value>
      <webElementGuid>d8b7535a-63b8-4cf7-a25b-f6a2a396c708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>2c3768a5-aaff-45dd-af7b-5e8831b7bdd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#account-dashboard</value>
      <webElementGuid>23524dcb-eb8d-419f-b554-bd2fd82fa816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>04222b74-9157-4b5f-b811-f49b029497cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>account-dashboard</value>
      <webElementGuid>f2494a1e-def8-4a12-91a3-99e9bbca1c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b8398105-932d-4f8c-be4f-53eb2223e932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thông tin tài khoản</value>
      <webElementGuid>723ad311-fd6a-47a6-ab4f-4738aba9d9c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account-dashboard-tab&quot;)</value>
      <webElementGuid>2c68391c-5801-412e-a48a-830e78a7ee17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='account-dashboard-tab']</value>
      <webElementGuid>6be09503-fd49-4190-9fe3-267dac2458e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='account-page-tab']/li/a</value>
      <webElementGuid>e79d5c57-2a74-473c-bd86-d5774f47e060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Thông tin tài khoản')]</value>
      <webElementGuid>5b6a819d-adb9-4c11-b838-bc16d161fee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tài khoản của tôi'])[3]/following::a[1]</value>
      <webElementGuid>fe657d54-48c8-4198-aff2-d03efa4c3293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang chủ'])[3]/following::a[1]</value>
      <webElementGuid>8b4c0f7b-cc7c-410e-ab19-0baa27cdef0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh sách đơn hàng'])[1]/preceding::a[1]</value>
      <webElementGuid>a72a08e1-5f7c-4ca7-b3ff-7297488e73b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thay đổi mật khẩu'])[1]/preceding::a[2]</value>
      <webElementGuid>a32d083e-b6ec-4121-81a0-da817d426100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thông tin tài khoản']/parent::*</value>
      <webElementGuid>07899ec3-807e-4ded-97be-2f6ce774a321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#account-dashboard')]</value>
      <webElementGuid>93122ce1-fdd0-46ea-a02d-aea0e0fe9883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/ul/li/a</value>
      <webElementGuid>1146529a-e0c9-45d6-9f72-9f0d63177659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'account-dashboard-tab' and @href = '#account-dashboard' and (text() = 'Thông tin tài khoản' or . = 'Thông tin tài khoản')]</value>
      <webElementGuid>5385deda-b2c7-4cbc-9781-f0607054cca7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
