<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_dangnhap</name>
   <tag></tag>
   <elementGuidId>d43b855a-19f8-4c3d-9ba6-ee8184e9b922</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.pe-7s-users</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='settingButton']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b79b0a40-05ef-4661-a4e5-c0f082ad2ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pe-7s-users</value>
      <webElementGuid>6e2c964b-822e-47fe-8b10-65072b7f7d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;settingButton&quot;)/i[@class=&quot;pe-7s-users&quot;]</value>
      <webElementGuid>0f29ec9b-90fc-4ff9-a457-3b03949eb3eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='settingButton']/i</value>
      <webElementGuid>94ca271f-9580-4280-a3e3-7329259bc768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/button/i</value>
      <webElementGuid>d2768806-d660-42f4-af46-835c4d7551ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
