<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_thongbaodangnhap</name>
   <tag></tag>
   <elementGuidId>cf43d6fb-55b5-4feb-bfdd-62adf60cebdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.notyf__wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[19]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>37b9a695-ee21-4eb7-b898-4cabc6500cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notyf__wrapper</value>
      <webElementGuid>b7bfcf9b-af79-4ea7-b452-9e38cfad37f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng nhập thành công</value>
      <webElementGuid>5bbbc66d-686f-4c78-889b-e3a3dc0af37f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;sizes customelements history pointerevents postmessage postmessage-structuredclones webgl websockets cssanimations csscolumns csscolumns-width csscolumns-span csscolumns-fill csscolumns-gap csscolumns-rule csscolumns-rulecolor csscolumns-rulestyle csscolumns-rulewidth csscolumns-breakbefore csscolumns-breakafter csscolumns-breakinside flexbox picture srcset webworkers&quot;]/body[1]/div[@class=&quot;notyf&quot;]/div[@class=&quot;notyf__toast notyf__toast--dismissible notyf__toast--upper notyf__toast--success notyf__toast--disappear&quot;]/div[@class=&quot;notyf__wrapper&quot;]</value>
      <webElementGuid>b74eb1e7-35c7-40b8-8c7d-4e4f7e6bdf08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[19]</value>
      <webElementGuid>b8685562-4c57-4a3d-bdfc-e3a788ce35a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập thành công'])[2]/preceding::div[5]</value>
      <webElementGuid>e2d120ab-481d-41cd-a204-efa7ee988ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>a17dd851-d06e-4d0a-b9f7-363cf0198cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Đăng nhập thành công' or . = 'Đăng nhập thành công')]</value>
      <webElementGuid>5f950b59-fdde-4537-a7fd-b1f2a56def9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
